#!/bin/bash

export LANG=en_US.UTF-8

if [[ $1 == "shell" ]]; then
    exec /bin/bash
fi

if [[ $1 == "start" ]]; then 
    /var/zcms/bin/pserve /var/zcms/production.ini
fi

if [[ $1 == "debug" ]]; then
    /var/zcms/bin/pserve /var/zcms/development.ini
fi

if [[ $1 == "buildout" ]]; then
    bin/buildout
fi
